name = "meiCloud - All You Need"
author = "Christopher John Czettel"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f85ee1252f5ab6eecdd6afaed5ad23403f25ada16ab0769b83641d12daeba89b"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
