name = "meiCloud - All You Need"
author = "Christopher John Czettel"
version = "0.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fd86504b62531009c43e973d1ba0f2eedc10ccc00ae96e95c5982990770d7d20"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.234"
