name = "meiCloud - All You Need"
author = "Christopher John Czettel"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "59aafcd934e6c61f4d0f258f3ca5a99da4017f4b45aadc15dd704b7a8ebf45b7"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.228"
